services:
  db:
    image: postgres:16
    container_name: minisns-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: minisns_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: minisns_postgres
    networks:
      - sns-network
    volumes:
      - C:/mini_sns_storage/postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  sns-redis:
    image: redis:latest
    container_name: minisns-redis
    ports:
      - "6379:6379"
    networks:
      - sns-network
    restart: always
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=MiniSNS:minisns-redis:6379
    ports:
      - "8088:8081"
    depends_on:
      - sns-redis
    networks:
      - sns-network
    restart: always

  minio:
    image: minio/minio
    container_name: minisns-minio
    ports:
      - "9000:9000" # API 통신용 (자바가 쓸 포트)
      - "9001:9001" # 관리자 화면용 (내가 볼 화면)
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    networks:
      - sns-network
    command: server /data --console-address ":9001"
    volumes:
      - C:/mini_sns_storage/minio_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node #소규모 개발이라서 node(서버)가 나 1대
      - xpack.security.enabled=false # 🚨로컬 개발용이므로 보안(비밀번호) 잠깐 해제🚨
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 512MB로 메모리 제한
    networks:
      - sns-network
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:9.3.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - sns-network
    volumes:
      - kibana_data:/usr/share/kibana/data

  kafka:
    image: apache/kafka:4.0.0
    container_name: minisns-kafka
    ports:
      - "9094:9094"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 #현재 서비스가 작기 때문에 카프카 서버 1대
    networks:
      - sns-network
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: minisns-kafka-ui
    ports:
      - "8989:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=sns-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - sns-network

  imgproxy:
    image: darthsim/imgproxy:latest
    container_name: minisns-imgproxy
    ports:
      - "8086:8080"
    environment:
      - IMGPROXY_BIND=0.0.0.0:8080
      - IMGPROXY_USE_S3=true
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
      - AWS_REGION=us-east-1
      - IMGPROXY_S3_ENDPOINT=http://minisns-minio:9000
    networks:
      - sns-network

  nginx:
    image: nginx:latest
    container_name: minisns-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - C:/mini_sns_storage/nginx_cache:/var/cache/nginx #윈도우의 C:/mini_sns_storage/nginx_cache와 리눅스의 /var/cache/nginx 연결
    depends_on:
      - imgproxy
    networks:
      - sns-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  sns-network:
    driver: bridge
volumes:
  es_data:
  kibana_data:
  kafka_data:
  nginx_cache:
