events {}

http {
    proxy_cache_path /var/cache/nginx keys_zone=image_cache:10m max_size=10g inactive=60d use_temp_path=off;

    server {
        listen 80;

        location / {
            proxy_pass http://imgproxy:8080;
            
            proxy_cache image_cache;
            proxy_cache_valid 200 30d;
            proxy_cache_use_stale error timeout updating;
            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}