### ===================================================================
### 테스트 흐름
### ===================================================================
### 1) API 호출 즉시 SoftDelete 실행
###     - posts 테이블의 status가 DELTE 로 바뀜 (소프트 삭제)
###     - 카프카 feed.post.deleted 발행: feed 모듈의 DB 캐시 및 Redis 데이터 삭제
### 2) 5초 후 HardDelete 실행
###     - post_tages, post_media, posts 순으로 DB 데이터 실제 삭제
###     - 카프카 post.minio.deleted 발행: MiniO 실제 파일 및 폴더 삭제

### ===================================================================
### 환경 변수 설정
### ===================================================================
@baseUrl = http://localhost/api/v1
@accessToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI4MyIsIm5pY2tuYW1lIjoi7L6M7Zmc7ZWc6rOwIiwiaWF0IjoxNzgyMDkxMTM2LCJleHAiOjE3ODIwOTI5MzZ9.wk_1JTZp-G4Z_ia4IGY7Nr--b95anj-lScPDlKmpK-f7nVT2G6QdelGk6sc3Wigj
@postId = 24
@currentUserId = 83

### ===================================================================
### 게시물 삭제 요청
### ===================================================================
DELETE {{baseUrl}}/posts/{{postId}}
Authorization: Bearer {{accessToken}}
