### 변수 설정 
@baseUrl = http://localhost/api/v1
@accessToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwibmlja25hbWUiOiLsvoztmZztlZzqs7AiLCJpYXQiOjE3ODQ3MDQ3MjIsImV4cCI6MTc4NDcwNjUyMn0.KsYqQa9QUHVt6lUo33mGgKUrHP1KA8EiVwtgOOHRdf0YBTSSAIiflWjm7y_6liWu
@userId = 1
@page = 0
@size = 2

### 1. Post 모듈 프로필 조회
GET {{baseUrl}}/posts/users/{{userId}}/profile?page={{page}}&size={{size}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}