### 변수설정
@baseUrl = http://localhost/api/v1
@email = test@example.com
@nickname = 김솜규링
@emailVerifyCode = 555625

### 1. 닉네임 중복 체크
GET {{baseUrl}}/users/nickname/exists?nickname={{nickname}}

### 2. 이메일 인증번호 발송 요청
Post {{baseUrl}}/auth/email/send
Content-Type: application/json

{
    "email": "{{email}}"
}

### 3. 이메일 인증번호 검증 요청
# @name emailVerifyApi
POST {{baseUrl}}/auth/email/verify
Content-Type: application/json

{
  "email": "{{email}}",
  "code": "{{emailVerifyCode}}"
}

### 4. 회원가입
POST {{baseUrl}}/auth/join
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "Password123!",
    "nickname": "{{nickname}}",
    "name": "이솜귤",
    "phoneNumber": "01012345678",
    "verificationToken": "{{emailVerifyApi.response.body.data.verifyToken}}",
    "deviceToken": "dummy_fcm_token"
}