### 변수 설정 
@baseUrl = http://localhost:8080/api/v1
@email = test1@example.com
@password = password123!


### 1. 일반 로그인(토큰 발급)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}