### 변수 설정 
@baseUrl = http://localhost:8080/api/v1
@accessToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI3Iiwibmlja25hbWUiOiLsvZTrlKnstIjrs7QiLCJpYXQiOjE3Nzg0MTYyNDksImV4cCI6MTc3ODQxODA0OX0.N_85cHLuaQqD1XvXKWMwsrFmnOs8EwFLuci_ZDb2vCxav8QOwcnq45JnIbFAzwUC

### 1. 게시물 등록
POST {{baseUrl}}/posts
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "mediaList": [
        {
            "mediaUrl": "C:/Users/rmawl/Downloads/테스트영상_2.mp4",
            "mediaType": "VIDEO",
            "cropState": {
                "crop": {"x": 10.5, "y": 25.0},
                "zoom": 1.5,
                "rotation": 0,
                "croppedAreaPixels": {
                    "width": 1080,
                    "height": 1080,
                    "x": 100,
                    "y": 100
                }
            }
        }
    ],
    "content": "미디어 업로드 최적화 테스트 중입니다. (더미 본문)",
    "tagUserIds": [8,9]
}