### 변수 설정 
@baseUrl = http://localhost/api/v1
@accessToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwibmlja25hbWUiOiLsvoztmZztlZzqs7AiLCJpYXQiOjE3ODU0NjQxNjEsImV4cCI6MTc4NTQ2NTk2MX0.16dtjegO_AK9QBKYeTuqUCW7kvnW6XPX_ykNqIZ-GSCCoxnr6PJYAU5w9dD7LbvO
@postId = 23


### 1. post 모듈이 요청한 데이터 전달 내부 api
GET {{baseUrl}}/feed?cursorId=1&size=10
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 2. 게시물 단건 조회 
GET {{baseUrl}}/feed/{{postId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}