### 변수 설정 
@baseUrl = http://localhost/api/v1
@accessToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwibmlja25hbWUiOiLsvoztmZztlZzqs7AiLCJpYXQiOjE3ODQ1OTg2MTEsImV4cCI6MTc4NDYwMDQxMX0.luFpZkeRcZs9iPxZ0PqtDKfjcfCOtCssdG8AFiokD29i0N2LsOXaEEevWKVtc3xC
@targetUserId = 2
@size = 2
@nextCursor = 2

### 1. 팔로우 성공 (나 1번 -> 2번 유저) 
POST {{baseUrl}}/follows/creat
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "targetUserId": 5
}

### 2. 자기 자신과 팔로우 예외 테스트 (나 1번 -> 1번)
POST {{baseUrl}}/follows/creat
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "targetUserId": 1
}

### 3. 존재하지 않는 유저에게 팔로우 (나 1번 -> 999번)
POST {{baseUrl}}/follows/creat
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "targetUserId": 999
}

### 4. 중복 팔로우 (나 1번 -> 2번, 이후에 또 2번에게 팔로우)
POST {{baseUrl}}/follows/creat
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "targetUserId": 2
}

// -------------------------------------------------------

### 1. 언팔로우 성공 (나 1번 -> 2번 유저) 
POST {{baseUrl}}/follows/destroy
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "targetUserId": 2
}

### 2. 자기 자신과 언팔로우 예외 테스트 (나 1번 -> 1번)
POST {{baseUrl}}/follows/destroy
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "targetUserId": 1
}

### 3. 존재하지 않는 유저에게 언팔로우 (나 1번 -> 999번)
POST {{baseUrl}}/follows/destroy
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "targetUserId": 999
}

// -------------------------------------------------------

### 1-1. 특정 유저의 팔로잉 목록 조회 (첫 페이지: cursor 없음)
GET {{baseUrl}}/users/{{targetUserId}}/followings?size={{size}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 1-2. 특정 유저의 팔로잉 목록 조회 (두번째 페이지: cursor 있음)
GET {{baseUrl}}/users/{{targetUserId}}/followings?cursor={{nextCursor}}&size={{size}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 2-1. 특정 유저의 팔로워 목록 조회 (첫 페이지: cursor 없음)
GET {{baseUrl}}/users/{{targetUserId}}/followers?size={{size}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}