### 변수 설정 
@baseUrl = http://localhost/api/v1
@accessToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwibmlja25hbWUiOiLsvZTrlKnrg5DsmLnsnbQiLCJpYXQiOjE3ODM5MDcxMjEsImV4cCI6MTc4MzkwODkyMX0.5Rwo2SxJBufMKKaJmlD8uLt_a_zLggX-oBcIDGgBZ35AF4E95zPPK-5MB_ieOOdj


### 1. 사용자 프로필 개인정보 조회 
GET {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 2. 닉네임 중복 체크
GET {{baseUrl}}/users/me/nickname/exists?nickname=코딩노예
Content-Type: application/json
Authorization: Bearer {{accessToken}}