server:
  port: 8085  # Notification API 서버는 8085 포트로 독립 가동
  servlet:
    context-path: /api

spring:
  kafka:
    bootstrap-servers: localhost:9094

minio:
  endpoint: http://localhost:9000
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucket: mini-sns
  default-image: /minio/mini-sns-default/default_loading_image.png