spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sns_db
    username: dev_user
    password: password123
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:9094
jwt:
  secret: ${JWT_SECRET}
kakao:
  client-id: ${KAKAO_RESTAPI_KEY}
  redirect-uri: ${KAKAO_REDIRECT_URI}
file:
  upload-dir: C:/mini-sns-uploads/
fmpg:
  path: C:/ffmpeg/bin/ffmpeg.exe
minio:
  endpoint: http://localhost:9000
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucket: mini-sns
  default-image: /minio/mini-sns-default/default_loading_image.png
logging:
  level:
    root: info
#    org.springframework.kafka: DEBUG
#    org.apache.kafka: DEBUG
#    org.springframework.data.elasticsearch.client.elc: TRACE
#    co.elastic.clients.transport: TRACE
#    org.elasticsearch.client.RestClient: TRACE
#    tracer: TRACE